version: "3"

services:
   shlink-web-client:
    image: shlinkio/shlink-web-client
    restart: always
    container_name: shlink-gui-Custom
    depends_on:
      - shlink
    ports:
      - 8082:8080